query user($language: String, $language1: String, $id: Int!){
    user(id: $id) {
        id
        username
        email
        createdAt
        context {
            user {
                id
                username
                email
                createdAt
                context {
                    domain
                }
                details{
                    __typename
                    ... on Guest {
                        region(language: $language)
                    }
                    ... on Member {
                        address
                    }
                    ... on Premium {
                        location
                        card {
                            number
                        }
                    }
                }
            }
            domain
        }
        details{
            __typename
            ... on Guest {
                region(language: $language1)
            }
            ... on Member {
                address
            }
            ... on Premium {
                location
                card {
                    number
                    type {
                        key
                    }
                }
            }
        }
    }
}