query user($language: String, $id: Int!){
    user(id: $id) {
        id
        username
        email
        createdAt
        details{
            __typename
            ... on Guest {
                region(language: $language)
            }
            ... on Member {
                address
            }
            ... on Premium {
                location
            }
        }
    }
}